export const LEMBAGA_LIST = [
  "Biro KEU",
  "Biro KSK",
  "Biro PPM",
  "Biro SPI",
  "Biro PSDA",
  "Kementerian ADKESMA",
  "Kementerian AKSPRO",
  "Kementerian ANSTRAT",
  "Kementerian PEMPU",
  "Kementerian PM",
  "Kementerian PSDM",
  "Kementerian SENIORA",
  "Kementerian PI",
  "Kementerian DAGRI",
  "Kementerian LUGRI",
  "Kementerian PENGMAS",
  "Kementerian MEDKRAF",
  "Kementerian MEDKOM",
  "Kementerian RISDAT",
] as const;
